export default class Debuffs {
  debuffName = {
    Confused: "Confused",
    DexterityNegative: "DexterityNegativey",
    DexterityDown: "DexterityDown",
    FocusNegative: "FocusNegativey",
    Frail: "Frail",
    NoDraw: "NoDraw",
    Poison: "Poison",
    Shackled: "Shackled",
    Slow: "Slow",
    StrengthNegative: "StrengthNegative",
    StrengthDown: "StrengthDown",
    Vulnerable: "Vulnerable",
    Weak: "Weak",
    Bias: "Bias",
    BlockReturn: "BlockReturn",
    Choked: "Choked",
    Constricted: "Constricted",
    CorpseExplosion: "CorpseExplosion",
    DrawReduction: "DrawReduction",
    Entangled: "Entangled",
    Fasting: "Fasting",
    Hex: "Hex",
    LockDown: "LockDown",
    Mark: "Mark",
    NoGuard: "NoGuard",
    WraithForm: "WraithForm",
  };

  debuffDescription = {
    Confused: "The costs of your cards are randomized on draw, from 0 to 3.",
    DexterityNegative: "Decreases Icon Block Block gained from cards by X.",
    DexterityDown: "At the end of your turn, lose X Icon Dexterity Dexterity.",
    FocusNegative: "Decreases the effectiveness of your Orbs by X.",
    Frail: "Block gained from cards is reduced by 25%.",
    NoDraw: "You may not draw any more cards this turn.",
    Poison:
      "At the beginning of its turn, the target loses X HP and 1 stack of Icon Poison Poison.",
    Shackled: "At the end of its turn, regains X Icon Strength Strength.",
    Slow: "The enemy receives (X*10)% more damage from attacks this turn. Whenever you play a card, increases X by 1.",
    StrengthNegative: "Decreases attack damage by X.",
    StrengthDown: "At the end of your turn, lose X Strength.",
    Vulnerable: "Target takes 50% more damage from attacks.",
    Weak: "Target deals 25% less attack damage.",
    Bias: "At the start of your turn, lose X Icon Focus Focus.",
    BlockReturn: "Whenever you attack this enemy, gain X Icon Block Block.",
    Choked:
      "Whenever you play a card this turn, the targeted enemy loses X HP.",
    Constricted: "At the end of your turn, take X damage.",
    CorpseExplosion:
      "On death, the enemy deals X times its Max HP worth of damage to all other enemies.",
    DrawReduction: "Draw 1 less card next X turns.",
    Entangled: "You may not play any Attacks this turn.",
    Fasting: "Gain X less Energy at the start of each turn.",
    Hex: "Whenever you play a non-Attack card, add X Dazed to your draw pile.",
    LockDown:
      "Lightning and Dark orbs deal 50% more damage (rounded down) to the targeted enemy.",
    Mark: "Whenever you play Pressure Points, all enemies with Mark lose X HP.",
    NoGuard:
      "You may not gain Icon Block Block from cards for the next X turns.",
    WraithForm: "Lose X Icon Dexterity Dexterity at the start of your turn.",
  };

  debuffStackable = {
    Confused: "No",
    DexterityNegative: "Intensity",
    DexterityDown: "Intensity",
    FocusNegative: "Intensity",
    Frail: "Duration",
    NoDraw: "No",
    Poison: "Intensity" + " " + "Duration",
    Shackled: "Intensity",
    Slow: "Intensity",
    StrengthNegative: "Intensity",
    StrengthDown: "Intensity",
    Vulnerable: "Duration",
    Weak: "Duration",
    Bias: "Intensity",
    BlockReturn: "Intensity",
    Choked: "Intensity",
    Constricted: "Intensity",
    CorpseExplosion: "Intensity",
    DrawReduction: "Duration",
    Entangled: "No",
    Fasting: "Intensity",
    Hex: "Intensity",
    LockDown: "Duration",
    Mark: "Intensity",
    NoGuard: "Duration",
    WraithForm: "Intensity",
  };

  debuffStacks = {
    Confused: 0,
    DexterityNegative: 0,
    DexterityDown: 0,
    FocusNegative: 0,
    Frail: 0,
    NoDraw: 0,
    Poison: 0,
    Shackled: 0,
    Slow: 0,
    StrengthNegative: 0,
    StrengthDown: 0,
    Vulnerable: 0,
    Weak: 0,
    Bias: 0,
    BlockReturn: 0,
    Choked: 0,
    Constricted: 0,
    CorpseExplosion: 0,
    DrawReduction: 0,
    Entangled: 0,
    Fasting: 0,
    Hex: 0,
    LockDown: 0,
    Mark: 0,
    NoGuard: 0,
    WraithForm: 0,
  };
}
